version: '3.8'

services:
  postgres:
    container_name: ap2_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=96334505
      - POSTGRES_DB=ap2